**we are going to create our own data-set with the help of Random and numpy and pandas library so let's do it**

In [ ]:
import random
import numpy as np
import pandas as pd

In [ ]:
total_rows = 3000

In [ ]:
# Define vehicle prices and details
vehicle_details = {
    'tvs iqube': {'Price': 146000, 'Top_Speed': 82, 'Km_in_Single_Charge': 145, 'Charging_Time_Hours': 4, 'Warranty_in_Years': 5, 'Vehicle_Weight': 128, 'Emi_Facility': 'Yes', 'Extra_Features': 'Yes','colour_availability':9},
    'bounce infinity e1': {'Price': 112000, 'Top_Speed': 65, 'Km_in_Single_Charge': 85, 'Charging_Time_Hours': 4, 'Warranty_in_Years': 5, 'Vehicle_Weight': 94, 'Emi_Facility': 'Yes', 'Extra_Features': 'Yes','colour_availability':6},
    'vida v1 plus': {'Price': 120000, 'Top_Speed': 80, 'Km_in_Single_Charge': 100, 'Charging_Time_Hours': 5.25, 'Warranty_in_Years': 5, 'Vehicle_Weight': 124, 'Emi_Facility': 'Yes', 'Extra_Features': 'Yes','colour_availability':3},
    'bajaj chetak urban': {'Price': 123000, 'Top_Speed': 73, 'Km_in_Single_Charge': 120, 'Charging_Time_Hours': 4.2, 'Warranty_in_Years': 5, 'Vehicle_Weight': 134, 'Emi_Facility': 'Yes', 'Extra_Features': 'Yes','colour_availability':4},
    'ola s1-pro gen-2': {'Price': 130000, 'Top_Speed': 120, 'Km_in_Single_Charge': 195, 'Charging_Time_Hours': 6.5, 'Warranty_in_Years': 8, 'Vehicle_Weight': 125, 'Emi_Facility': 'Yes', 'Extra_Features': 'Yes','colour_availability':5}
}

# Generate customer IDs
customer_id = list(range(1, total_rows + 1))

# Generate customer ages
customer_age = np.random.randint(18, 73, size=total_rows)

# Generate random vehicle names
vehicle_name = [random.choice(list(vehicle_details.keys())) for _ in range(total_rows)]

# Generate current price based on vehicle name
current_price = [vehicle_details[name]['Price'] for name in vehicle_name]

# Generate other columns based on vehicle name
warranty_in_years = [vehicle_details[name]['Warranty_in_Years'] for name in vehicle_name]
emi_facility = [vehicle_details[name]['Emi_Facility'] for name in vehicle_name]
top_speed_in_km = [vehicle_details[name]['Top_Speed'] for name in vehicle_name]
km_in_single_charge = [vehicle_details[name]['Km_in_Single_Charge'] for name in vehicle_name]
charging_time_hours = [vehicle_details[name]['Charging_Time_Hours'] for name in vehicle_name]
extra_features = [vehicle_details[name]['Extra_Features'] for name in vehicle_name]
vehicle_weight = [vehicle_details[name]['Vehicle_Weight'] for name in vehicle_name]
colour_availability = [vehicle_details[name]['colour_availability'] for name in vehicle_name]

In [ ]:
area= [random.choice(['Urban','Rural']) for _ in range(total_rows)]
service_ratings = np.random.randint(2,6, size=total_rows)

In [ ]:
# Print vehicle details for checking
for i in range(total_rows):
    print(f"Customer ID: {customer_id[i]}, area: {area[i]}, service_ratings: {service_ratings[i]}, Vehicle Name: {vehicle_name[i]}, Customer Age: {customer_age[i]}, Current Price: {current_price[i]}, Warranty in Years: {warranty_in_years[i]}, Emi Facility: {emi_facility[i]}, colour_availability:{colour_availability[i]}, Top Speed in km: {top_speed_in_km[i]}, Km in Single Charge: {km_in_single_charge[i]}, Charging Time in Hours: {charging_time_hours[i]}, Extra Features: {extra_features[i]}, Vehicle Weight: {vehicle_weight[i]}")

In [ ]:
# Create DataFrame
data = {
    'customer_id': customer_id,
    'vehicle_name': vehicle_name,
    'customer_age': customer_age,
    'area': area,
    'current_price': current_price,
    'warranty_in_years': warranty_in_years,
    'emi_facility': emi_facility,
    'top_speed_in_km': top_speed_in_km,
    'km_in_single_charge': km_in_single_charge,
    'charging_time_hours': charging_time_hours,
    'service_ratings': service_ratings,
    'extra_features': extra_features,
    'vehicle_weight': vehicle_weight,
    'colour_availability':colour_availability
}

df = pd.DataFrame(data)

In [ ]:
#let's check pur data_set, how it looks like
df.head(20)

,customer_id,vehicle_name,customer_age,area,current_price,warranty_in_years,emi_facility,top_speed_in_km,km_in_single_charge,charging_time_hours,service_ratings,extra_features,vehicle_weight,colour_availability
0,1,bajaj chetak urban,27,Rural,123000,5,Yes,73,120,4.20,3,Yes,134,4
1,2,bounce infinity e1,61,Urban,112000,5,Yes,65,85,4.00,5,Yes,94,6
2,3,ola s1-pro gen-2,19,Urban,130000,8,Yes,120,195,6.50,3,Yes,125,5
3,4,vida v1 plus,22,Urban,120000,5,Yes,80,100,5.25,5,Yes,124,3
4,5,bajaj chetak urban,64,Urban,123000,5,Yes,73,120,4.20,2,Yes,134,4
5,6,ola s1-pro gen-2,48,Rural,130000,8,Yes,120,195,6.50,2,Yes,125,5
6,7,vida v1 plus,22,Rural,120000,5,Yes,80,100,5.25,4,Yes,124,3
7,8,tvs iqube,63,Rural,146000,5,Yes,82,145,4.00,5,Yes,128,9
8,9,ola s1-pro gen-2,30,Urban,130000,8,Yes,120,195,6.50,4,Yes,125,5
9,10,tvs iqube,41,Urban,146000,5,Yes,82,145,4.00,2,Yes,128,9
10,11,ola s1-pro gen-2,72,Urban,130000,8,Yes,120,195,6.50,5,Yes,125,5
11,12,vida v1 plus,18,Rural,120000,5,Yes,80,100,5.25,2,Yes,124,3
12,13,ola s1-pro gen-2,22,Urban,130000,8,Yes,120,195,6.50,4,Yes,125,5
13,14,ola s1-pro gen-2,36,Rural,130000,8,Yes,120,195,6.50,3,Yes,125,5
14,15,bounce infinity e1,72,Rural,112000,5,Yes,65,85,4.00,5,Yes,94,6
15,16,ola s1-pro gen-2,52,Urban,130000,8,Yes,120,195,6.50,5,Yes,125,5
16,17,vida v1 plus,37,Rural,120000,5,Yes,80,100,5.25,5,Yes,124,3
17,18,vida v1 plus,33,Rural,120000,5,Yes,80,100,5.25,2,Yes,124,3
18,19,ola s1-pro gen-2,42,Rural,130000,8,Yes,120,195,6.50,4,Yes,125,5
19,20,bajaj chetak urban,24,Rural,123000,5,Yes,73,120,4.20,2,Yes,134,4

In [ ]:
#now let's save are data_set so we can use it in our customer segmentation analysis & model building
df.to_csv('EV__two-wheeler_data.csv', index=False)
print("Done Bro Data is now saved, Go Use It!....")

Done Bro Data is now saved, Go Use It!....

**Source of Real details About EV** 'https://www.bikedekho.com/electric-scooters'